//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFacturation.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyFacturation.Ressources.ValidationMessage", typeof(ValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All lines must have a description..
        /// </summary>
        internal static string AllQuoteLineMustHaveDescriptionErrorMessage {
            get {
                return ResourceManager.GetString("AllQuoteLineMustHaveDescriptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change the quote status.
        /// </summary>
        internal static string ChangingQuoteStatusErrorMessage {
            get {
                return ResourceManager.GetString("ChangingQuoteStatusErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the client, please try again..
        /// </summary>
        internal static string ClientCreateErrorMessage {
            get {
                return ResourceManager.GetString("ClientCreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the client, please try again..
        /// </summary>
        internal static string ClientDeleteErrorMessage {
            get {
                return ResourceManager.GetString("ClientDeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A client must have either a first and last name, or a company name..
        /// </summary>
        internal static string ClientNameOrCompany {
            get {
                return ResourceManager.GetString("ClientNameOrCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the client, please try again..
        /// </summary>
        internal static string ClientUpdateErrorMessage {
            get {
                return ResourceManager.GetString("ClientUpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the quote, please try again..
        /// </summary>
        internal static string CreatingQuoteErrorMessage {
            get {
                return ResourceManager.GetString("CreatingQuoteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the client..
        /// </summary>
        internal static string GettingClientErrorMessage {
            get {
                return ResourceManager.GetString("GettingClientErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve clients..
        /// </summary>
        internal static string GettingClientListErrorMessage {
            get {
                return ResourceManager.GetString("GettingClientListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the quote..
        /// </summary>
        internal static string GettingQuoteErrorMessage {
            get {
                return ResourceManager.GetString("GettingQuoteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve quotes..
        /// </summary>
        internal static string GettingQuoteListErrorMessage {
            get {
                return ResourceManager.GetString("GettingQuoteListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the quote status history..
        /// </summary>
        internal static string GettingQuoteStatusHistoryErrorMessage {
            get {
                return ResourceManager.GetString("GettingQuoteStatusHistoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid..
        /// </summary>
        internal static string InvalidEmailAdress {
            get {
                return ResourceManager.GetString("InvalidEmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is invalid..
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change status of an archived quote..
        /// </summary>
        internal static string QuoteAlreadyArchivedErrorMessage {
            get {
                return ResourceManager.GetString("QuoteAlreadyArchivedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All lines must have a quantity and unit price OR all lines must be empty..
        /// </summary>
        internal static string QuoteLinesMustBeFulledOrEmpty {
            get {
                return ResourceManager.GetString("QuoteLinesMustBeFulledOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a quote without any item lines..
        /// </summary>
        internal static string QuoteMusteHaveLinesToBeCreated {
            get {
                return ResourceManager.GetString("QuoteMusteHaveLinesToBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update a quote already sent..
        /// </summary>
        internal static string QuoteNotInDraftStatusErrorMessage {
            get {
                return ResourceManager.GetString("QuoteNotInDraftStatusErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to correct a quote not sent..
        /// </summary>
        internal static string QuoteNotSentStatusErrorMessage {
            get {
                return ResourceManager.GetString("QuoteNotSentStatusErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the quote, please try again..
        /// </summary>
        internal static string QuoteUpdateErrorMessage {
            get {
                return ResourceManager.GetString("QuoteUpdateErrorMessage", resourceCulture);
            }
        }
    }
}
